bot:
  name: PlanAceBot
  token: 7363455230:AAE4WqdV7VNEbg3FvcD-QGTu8XcqHZWCgWM

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/devmax_account
    username: devmax_account_admin
    password: p;rXG1Y75E
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      connectionTimeout: 30000
      maxLifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  application:
    name: PlanAceBot

server:
  port: 8443