bot:
  name: PlanAceBot
  token: unknown

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:54320/devMax_account
    username: devMax_account_admin
    password: g*nLx&5oSQQ
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      connectionTimeout: 30000
      maxLifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  application:
    name: PlanAceBot

server:
  port: 8443