bot:
  name: PlanAceBot
  token: unknown

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/devMax_account
    username: devMax_account_admin
    password: g*nLx&5oSQQ

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  application:
    name: PlanAceBot

server:
  port: 8443